version: "3.9"

services:
  user-service:
    build: ./backend/services/user-service
    container_name: user-service
    ports:
      - "3001:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
    networks:
      - app-network

  restaurant-service:
    build: ./backend/services/restaurant-service
    container_name: restaurant-service
    ports:
      - "3002:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
    networks:
      - app-network

  order-service:
    build: ./backend/services/order-service
    container_name: order-service
    ports:
      - "3003:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
    networks:
      - app-network

  delivery-service:
    build: ./backend/services/delivery-service
    container_name: delivery-service
    ports:
      - "3004:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
    networks:
      - app-network

  payment-service:
    build: ./backend/services/payment-service
    container_name: payment-service
    ports:
      - "3005:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
    networks:
      - app-network

  gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "8080:80"
    volumes:
      - ./backend/gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - restaurant-service
      - order-service
      - delivery-service
      - payment-service
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: zomato-frontend
    ports:
      - "80:80"
    depends_on:
      - gateway
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

