apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-nginx-config
  namespace: zomato

data:
  nginx.conf: |-
    events {
        worker_connections 1024;
    }

    http {

        types {
            text/html                             html htm shtml;
            text/css                              css;
            text/xml                              xml;
            image/gif                             gif;
            image/jpeg                            jpeg jpg;
            application/javascript                js;
            application/json                      json;
            image/png                             png;
            image/svg+xml                         svg svgz;
            application/wasm                      wasm;
            font/woff                             woff;
            font/woff2                            woff2;
        }

        default_type application/octet-stream;

        sendfile on;
        keepalive_timeout 65;

        gzip on;

        log_format main '$remote_addr - $remote_user [$time_local] '
                        '"$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent"';

        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log warn;

        server {
            listen 80;
            server_name localhost;

            proxy_connect_timeout 5s;
            proxy_send_timeout 10s;
            proxy_read_timeout 10s;

            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;

            location /health {
                access_log off;
                default_type application/json;
                return 200 '{"status":"UP"}';
            }

            location /api/users/ {

                if ($request_method = OPTIONS) {
                    return 204;
                }

                proxy_pass http://user-service.zomato.svc.cluster.local:3000/;

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location /api/restaurants/ {

                if ($request_method = OPTIONS) {
                    return 204;
                }

                proxy_pass http://restaurant-service.zomato.svc.cluster.local:3000/api/restaurants/;

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location /api/cuisines {
                proxy_pass http://restaurant-service.zomato.svc.cluster.local:3000/api/cuisines;
            }

            location /api/categories {
                proxy_pass http://restaurant-service.zomato.svc.cluster.local:3000/api/categories;
            }

            location /api/cart/ {
                proxy_pass http://order-service.zomato.svc.cluster.local:3000/api/cart/;
            }

            location /api/orders/ {
                proxy_pass http://order-service.zomato.svc.cluster.local:3000/api/orders/;
            }

            location /api/orders {
                proxy_pass http://order-service.zomato.svc.cluster.local:3000/api/orders;
            }

            location /api/deliveries/ {
                proxy_pass http://delivery-service.zomato.svc.cluster.local:3000/api/deliveries/;
            }

            location /api/tracking/ {
                proxy_pass http://delivery-service.zomato.svc.cluster.local:3000/api/tracking/;
            }

            location /api/payments/ {
                proxy_pass http://payment-service.zomato.svc.cluster.local:3000/api/payments/;
            }

            location /api/payments {
                proxy_pass http://payment-service.zomato.svc.cluster.local:3000/api/payments;
            }

            location / {
                return 404;
            }
        }
    }