apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
  labels:
    app: promtail
    app.kubernetes.io/name: promtail
    app.kubernetes.io/component: logging
data:
  promtail.yml: |
    server:
      http_listen_port: 3101
      grpc_listen_port: 3102

    clients:
      - url: http://loki:3100/loki/api/v1/push

    positions:
      filename: /tmp/positions.yaml

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
          - match:
              stage: regex
              regex:
                node_hostname: ' (.+)'
          - labels:
              node_hostname: ''
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_host_ip]
            target_label: node_hostname

      - job_name: kubernetes-nodes
        static_configs:
          - targets:
              - localhost
            labels:
              job: kubernetes-nodes
              path: /var/log/messages
